CHANGELOG.md, PSGSuite/PSGSuite.psd1, PSGSuite/Public/Users/Update-GSUser.ps1, README.md
* Fixed: `Update-GSUser -CustomSchemas @{schema = @{field = "value"}}` resulting in null array (Resolve [Issue #39](https://github.com/scrthq/PSGSuite/issues/39))
=> !build fixes for #39

CHANGELOG.md, PSGSuite/PSGSuite.psd1, PSGSuite/Private/ListPrivate/Get-GSUserListPrivate.ps1, PSGSuite/Public/Drive/Get-GSDriveFileList.ps1, PSGSuite/Public/Users/Get-GSUser.ps1, README.md
* Fixed/Added: Specific domain support for listing users with `Get-GSUser -Filter $filter -Domain domain2.com` to allow customers with multiple domains to only list users for a specific domain instead of just the entire customer or domain saved in the config. (Resolve [Issue #32](https://github.com/scrthq/PSGSuite/issues/32))
* Added: Better verbose output in when listing users
* Fixed: Performance increase in `Get-GSDriveFileList` but returning DriveFile objects as it iterates through each page instead of storing in an array and returning the array at the end (Resolve [Issue #38](https://github.com/scrthq/PSGSuite/issues/38))
=> !build v2.5.3 - multi domain support for #32 and perf increase for #38

CHANGELOG.md, PSGSuite/PSGSuite.psd1, PSGSuite/Public/Calendar/Update-GSCalendarEvent.ps1, README.md
* Fixed: `Update-GSCalendarEvent` had default values set for LocalStartDateTime and LocalEndDateTime parameters, causing those to always update the event unexpectedly if a start and/or end datetime was not passed when running the command ([Issue #59](https://github.com/scrthq/PSGSuite/issues/59))
=> pushing fixes for issue #59

CHANGELOG.md, PSGSuite/PSGSuite.psd1, PSGSuite/Public/Groups/Get-GSGroup.ps1, README.md
* Fixed: `Get-GSGroup` failing when using `List` ParameterSet and the `Fields` Parameter ([Issue #63](https://github.com/scrthq/PSGSuite/issues/63))
=> fix for issue #63

.gitignore, CHANGELOG.md, PSGSuite/PSGSuite.psd1, PSGSuite/Public/Drive/Update-GSDriveFile.ps1, README.md
* Updated: Added `Path` parameter to `Update-GSDriveFile` to allow updating a file's contents in Drive using a local file path.
=> !build v2.10.1 add Path param to Update-GSDriveFile

CHANGELOG.md, PSGSuite/PSGSuite.psd1, PSGSuite/Public/Drive/Add-GSDocContent.ps1, PSGSuite/Public/Drive/Export-GSDriveFile.ps1, PSGSuite/Public/Drive/Get-GSDocContent.ps1, PSGSuite/Public/Drive/Set-GSDocContent.ps1, PSGSuite/Public/Drive/Update-GSDriveFile.ps1, README.md
* Added: `Get-GSDocContent`, `Set-GSDocContent` & `Add-GSDocContent` to establish functional parity with `Get-Content`, `Set-Content` & `Add-Content` in regards to working with Google Docs ([Issue #56](https://github.com/scrthq/PSGSuite/issues/56))
=> !build v2.10.2 add *-GSDocContent functions

CHANGELOG.md, PSGSuite/PSGSuite.psd1, PSGSuite/Public/Drive/Remove-GSDrivePermission.ps1, PSGSuite/Public/Gmail/Get-GSGmailFilter.ps1, PSGSuite/Public/Gmail/Get-GSGmailSMIMEInfo.ps1, PSGSuite/Public/Gmail/New-GSGmailSMIMEInfo.ps1, PSGSuite/Public/Gmail/Remove-GSGmailSMIMEInfo.ps1, README.md, Tests/PSGSuite.Tests.ps1
* Added: `Get-GSGmailSMIMEInfo`, `Remove-GSGmailSMIMEInfo` & `New-GSGmailSMIMEInfo` to get, delete and insert S/MIME info for a user, respectively ([Issue #57](https://github.com/scrthq/PSGSuite/issues/57))
=> !build v2.11.0 S/MIME info functions to resolve #57

.gitignore, CHANGELOG.md, PSGSuite/PSGSuite.psd1, PSGSuite/Private/Legacy/Get-GSToken.ps1, PSGSuite/Private/ListPrivate/Get-GSGroupListPrivate.ps1, PSGSuite/Private/ListPrivate/Get-GSGroupMemberListPrivate.ps1, PSGSuite/Private/ListPrivate/Get-GSShortUrlListPrivate.ps1, PSGSuite/Private/ListPrivate/Get-GSUserASPListPrivate.ps1, PSGSuite/Private/ListPrivate/Get-GSUserSchemaListPrivate.ps1, PSGSuite/Private/ListPrivate/Get-GSUserTokenListPrivate.ps1, PSGSuite/Public/Chat/Get-GSChatSpace.ps1, PSGSuite/Public/Chat/Send-GSChatMessage.ps1, PSGSuite/Public/Chat/Update-GSChatMessage.ps1, PSGSuite/Public/Configuration/Get-GSChatConfig.ps1, PSGSuite/Public/Configuration/Set-PSGSuiteConfig.ps1, PSGSuite/Public/Helpers/Add-GSChatOnClick.ps1, PSGSuite/Public/Users/Get-GSUser.ps1, README.md, appveyor.yml
* Fixed: Private list functions to check if a value is actually returned before adding members to the returned objects ([Issue #77](https://github.com/scrthq/PSGSuite/issues/77))
* Added: `Update-GSChatMessage` to allow updating existing messages in Chat (i.e. on Card Clicked events)
* Updated: Order of parameters in `Get-GSToken` to place `Scopes` first, as it's the only required parameter
* Updated: `Get-GSChatSpace` now updates the config with Space names/shortnames for ease of use
* Updated: `Send-GSChatMessage` to also support calling the REST API as an additional option. This is necessary for PoshBot due to the deserialization of objects passed back to result parser breaking the Google SDK type references
* Updated: `Get-GSChatConfig` to always fetch the latest config if no …
=> !build v2.13.0 to resolve #77 and update commands to work with PoshBot.GChat.Backend

CHANGELOG.md, PSGSuite/PSGSuite.psd1, PSGSuite/Public/Helpers/Add-GSUserOrganization.ps1, PSGSuite/Public/Users/New-GSUser.ps1, PSGSuite/Public/Users/Update-GSUser.ps1, README.md
* [Issue #83](https://github.com/scrthq/PSGSuite/issues/83)
* Added: `Add-GSUserOrganization` to create UserOrganization objects
* Updated: `Update-GSUser` and `New-GSUser` to include Organizations parameter and cleaned up logic for other Generic.List type parameters to ensure functionality
=> !build v2.13.2 to include Organization support for #83

CHANGELOG.md, PSGSuite/PSGSuite.psd1, PSGSuite/Public/Classroom/Add-GSCourseParticipant.ps1, PSGSuite/Public/Classroom/Get-GSClassroomUserProfile.ps1, PSGSuite/Public/Classroom/Get-GSCourseParticipant.ps1, PSGSuite/Public/Gmail/Remove-GSGmailMessage.ps1, PSGSuite/Public/Gmail/Update-GSGmailMessageLabels.ps1, PSGSuite/Public/Users/Get-GSUser.ps1, README.md
* [Issue #87](https://github.com/scrthq/PSGSuite/issues/87)
* Fixed `Add-GSCourseParticipant` error: `"Cannot convert the "student@uni.edu" value of type "System.String" to type "Google.Apis.Classroom.v1.Data.Student"."`
* Set `$request.Fields = "*"` for `Get-GSCourseParticipant` and `Get-GSClassroomUserProfile` to return all available fields for the `Profile`, including `EmailAddress`
* [Issue #93](https://github.com/scrthq/PSGSuite/issues/93)
* Added: `MaxToModify` parameter to `Remove-GSGmailMessage` and `Update-GSGmailMessageLabels` in the `Filter` parameter set to prevent removing/updating more messages than expected when using a filter to gather the list of messages to update.
* Added: `Id` alias for `User` parameter on `Get-GSUser` for better pipeline support
=>  !build v2.15.3 with updates for #87 and #93

PSGSuite/Public/Helpers/Add-GSUserRelation.ps1, PSGSuite/Public/Users/New-GSUser.ps1, PSGSuite/Public/Users/Update-GSUser.ps1
https://github.com/scrthq/PSGSuite/issues/129
=> Add Support for User Relation

CHANGELOG.md, PSGSuite/PSGSuite.psd1, PSGSuite/Public/Helpers/Add-GSUserRelation.ps1, PSGSuite/Public/Sheets/Get-GSSheetInfo.ps1, PSGSuite/Public/Users/Update-GSUser.ps1, README.md
* [PR #130](https://github.com/scrthq/PSGSuite/pull/130) / [Issue #129](https://github.com/scrthq/PSGSuite/issues/129)
* Added: Support for UserRelations management in `New-GSUser -Relations $relations` and `Update-GSUser -Relations $relations` via `Add-GSUserRelation` helper function. - _Thanks, [@mattwoolnough](https://github.com/mattwoolnough)!_
* Added: Logic to `Update-GSUser` to enable clearing of all values for user properties `Phones`, `ExternalIds`, `Organizations`, and `Relations` by REST API call via passing `$null` as the value when calling `Update-GSUser`. - _Thanks, [@mattwoolnough](https://github.com/mattwoolnough)!_
* [Issue #129](https://github.com/scrthq/PSGSuite/issues/129)
* Fixed: Documentation for `Get-GSSheetInfo` around the `Fields` parameter.
* Added: Additional …
=> pushing updates for v2.21.0

CHANGELOG.md, PSGSuite/PSGSuite.psd1, PSGSuite/Public/Authentication/Get-GSToken.ps1, PSGSuite/Public/Authentication/New-GoogleService.ps1, PSGSuite/Public/Configuration/Get-PSGSuiteConfig.ps1, PSGSuite/Public/Configuration/Set-PSGSuiteConfig.ps1, PSGSuite/Public/Configuration/Switch-PSGSuiteConfig.ps1, README.md, build.ps1
* [Issue #131](https://github.com/scrthq/PSGSuite/issues/131) - _Free/standard Google Account support_
* Fixed: Handling of scopes in `New-GoogleService` for authentication when a client_secrets.json file is used instead of the typical .p12 key.
* Updated: Documentation to show how to use an account that is not a G Suite admin or G Suite user at all with PSGSuite
* Updated: `*-PSGSuiteConfig` commands now store the client_secrets.json string contents directly on the encrypted config once provided either the path or the string contents directly, allowing users to remove any plain text credentials once loaded into the encrypted config.
* Updated: `Get-GSToken` now uses `New-GoogleService` under the hood, so `client_secrets.json` will work with Contacts API.
=> adding content for v2.21.1

CHANGELOG.md, PSGSuite/PSGSuite.psd1, PSGSuite/Public/Drive/Start-GSDriveFileUpload.ps1, README.md
* [Issue #136](https://github.com/scrthq/PSGSuite/issues/136)
* Fixed: `Start-GSDriveFileUpload` failing when specifying a user other than the Admin user to do the upload as.
=> v2.21.2 - fix for #136

.gitignore, CHANGELOG.md, PSGSuite/PSGSuite.psd1, PSGSuite/Public/Authentication/New-GoogleService.ps1, PSGSuite/Public/Configuration/Export-PSGSuiteConfig.ps1, PSGSuite/Public/Configuration/Get-PSGSuiteConfig.ps1, PSGSuite/Public/Configuration/Import-PSGSuiteConfig.ps1, PSGSuite/Public/Configuration/Set-PSGSuiteConfig.ps1, PSGSuite/Public/Configuration/Switch-PSGSuiteConfig.ps1, README.md, psake.ps1
* Miscellaneous: _Config management and portability updates_
* Added: `Export-PSGSuiteConfig` function to export key parts of your config in a transportable JSON file.
* Added: `Import-PSGSuiteConfig` function to import a config from a JSON file (i.e. one created with `Export-PSGSuiteConfig`) or from a JSON string (i.e. stored in a secure variable in a CI/CD system.)
* Updated: All config functions now store the P12Key or the ClientSecrets JSON string in the encrypted config directly. This is to allow removal of the secrets files as well as enable PSGSuite to run in a contained environment via importing the config from a secure JSON string.
* Updated: `[Get|Set|Switch]-PSGSuiteConfig` to include the P12Key and ClientSecrets parameters that enable housing of the key/secret directly on the …
=> v2.22.0 - enhanced PSGSuiteConfig management and portability

CHANGELOG.md, PSGSuite/PSGSuite.psd1, PSGSuite/Public/Drive/Start-GSDriveFileUpload.ps1, README.md
* [Issue #144](https://github.com/scrthq/PSGSuite/issues/144)
* Updated: `Start-GSDriveFileUpload` to not call `[System.Console]::CursorVisible` when `$Host` is PowerShell ISE
=> fixed [System.Console]::CursorVisible call error from ISE

CHANGELOG.md, PSGSuite/PSGSuite.psd1, PSGSuite/Public/Reports/Get-GSUsageReport.ps1, README.md
**This update changes the output of `Get-GSUsageReport` -- please review the output changes before updating if you have scripts that use that function!!**
* Fixed: `Get-GSUsageReport` wasn't displaying critical report information (such as the Entity info) due to Select-Object being hardcoded. Function has been updated to parse the resulting Parameters and Entity info out to the top-level object.
* Added: `Flat` switch to specify that the parsed properties match what GAM returns, i.e. `'gmail:num_outbound_unencrypted_emails' = 6`. Normal behavior would be to parse that into an ordered dictionary, i.e. `gmail['num_outbound_unencrypted_emails'] = 6`, so that only `gmail` is seen from the top level object and all relevant report data is captured in the underlying dictionary.
* Added: `Raw` …
=> v2.23.1 - fixes for Get-GSUsageReport

CHANGELOG.md, PSGSuite/PSGSuite.psd1, PSGSuite/Public/Drive/Add-GSDrivePermission.ps1, README.md
* [Issue #182](https://github.com/scrthq/PSGSuite/issues/182) - _Thanks, [@aitcriver](https://github.com/aitcriver)!_
* Added: `FileOrganizer` role to `ValidateSet` for parameter `Role` on function `Add-GSDrivePermission`
=> pushing up v2.26.3 with fix for #182

CHANGELOG.md, PSGSuite/PSGSuite.psd1, PSGSuite/Private/Get-SafeFileName.ps1, README.md
* [Issue #188](https://github.com/scrthq/PSGSuite/issues/188)
* Fixed: Get-SafeFileName correctly replaces special RegEx chars with underscores as well.
=> !deploy v2.28.1 to resolve #188

CHANGELOG.md, PSGSuite/PSGSuite.psd1, PSGSuite/Public/Security/Update-GSChromeOSDevice.ps1, README.md
* [Issue #194](https://github.com/scrthq/PSGSuite/issues/194)
* Fixed: Parameters not setting correctyl on `Update-GSChromeOSDevice`:
* `AnnotatedAssetId [string]`
* `AnnotatedLocation [string]`
* `AnnotatedUser [string]`
* `Notes [string]`
=> pushing fix for #194 for Update-GSChromeDevice

CHANGELOG.md, PSGSuite/Aliases/PSGSuite.Aliases.ps1, PSGSuite/PSGSuite.psd1, PSGSuite/Public/Drive/Copy-GSDriveFile.ps1, PSGSuite/Public/Drive/Export-GSDriveFile.ps1, PSGSuite/Public/Drive/Hide-GSDrive.ps1, PSGSuite/Public/Drive/New-GSDrive.ps1, PSGSuite/Public/Drive/New-GSDriveFile.ps1, PSGSuite/Public/Drive/Remove-GSDrive.ps1, PSGSuite/Public/Drive/Show-GSDrive.ps1, PSGSuite/Public/Drive/Update-GSDrive.ps1, PSGSuite/Public/Groups/Update-GSGroupSettings.ps1, README.md
* [Issue #201](https://github.com/scrthq/PSGSuite/issues/201)
* Fixed: Fields parameter on remaining `*-GSDriveFile` functions
* [Issue #197](https://github.com/scrthq/PSGSuite/issues/197)
* Updated: All remaining `*-TeamDrive` functions now use the new Drives namespace. All previous functions names have been converted to aliases to maintain backwards compatibility.
* Added: `Hide-GSDrive`
* Added: `Show-GSDrive`
* [Issue #184](https://github.com/scrthq/PSGSuite/issues/184)
* Added: `EnableCollaborativeInbox` parameter to `Update-GSGroupSettings`
* Added: `WhoCanDiscoverGroup` parameter to `Update-GSGroupSettings`
=> !deploy v2.29.0 with multiple fixes

CHANGELOG.md, PSGSuite/PSGSuite.psd1, PSGSuite/Public/Drive/Add-GSDrivePermission.ps1, PSGSuite/Public/Drive/Get-GSDriveFileList.ps1, PSGSuite/Public/Drive/Get-GSDriveFolderSize.ps1, PSGSuite/Public/Drive/Get-GSDrivePermission.ps1, PSGSuite/Public/Drive/Get-GSDriveRevision.ps1, PSGSuite/Public/Drive/Remove-GSDrivePermission.ps1, PSGSuite/Public/Drive/Remove-GSDriveRevision.ps1, PSGSuite/Public/Drive/Update-GSDriveRevision.ps1, PSGSuite/Public/Gmail/Get-GSGmailMessage.ps1, PSGSuite/Public/Gmail/Get-GSGmailMessageList.ps1, PSGSuite/Public/Users/Update-GSUser.ps1, README.md, psake.ps1
* [Issue #193](https://github.com/scrthq/PSGSuite/issues/193)
* Added: Drive Revision functions:
* `Get-GSDriveRevision`
* `Remove-GSDriveRevision`
* `Update-GSDriveRevision`
* [Issue #210](https://github.com/scrthq/PSGSuite/issues/210)
* Fixed: `Update-GSUser` was not accepting User ID's as the User parameter
* [Issue #209](https://github.com/scrthq/PSGSuite/issues/209)
* Added: Support for inline image downloading with `Get-GSGmailMessage` where the image is not included on the Attachments property of the parsed message object.
* Fixed: `Get-GSGmailMessage` will now automatically set the `Format` to `Raw` if either `ParseMessage` or `SaveAttachmentsTo` is passed, as `ParseMessage` is a requirement in order to be able to access the message attachments as needed.
* [Issue …
=> Multiple fixes and features to add

CHANGELOG.md, PSGSuite/PSGSuite.psd1, PSGSuite/Public/Authentication/New-GoogleService.ps1, PSGSuite/Public/Security/Remove-GSUserASP.ps1, PSGSuite/Public/Security/Remove-GSUserToken.ps1, PSGSuite/Public/Users/Update-GSUser.ps1, README.md, build.ps1, ci/AzurePipelinesHelpers.ps1
* [Issue #222](https://github.com/scrthq/PSGSuite/issues/222)
* Fixed: `Remove-GSUserASP` and `Remove-GSUserToken` not removing all when no Id is passed due to no service being created.
* [Issue #225](https://github.com/scrthq/PSGSuite/issues/225)
* Added: `RecoveryEmail` and `RecoveryPhone` parameters to `Update-GSUser`
* [Issue #189](https://github.com/scrthq/PSGSuite/issues/189)
* Removed `$env:UserName` from the application name when creating the client in `New-GoogleService` to prevent errors with the underlying .NET SDK.
* Miscellaneous
* Fixed: Corrected logic on the `FullName` parameter on `Update-GSUser` to parse the name parts.
* Updated Google .NET SDKs to latest versions.
=> !deploy v2.31.1

CHANGELOG.md, CONTRIBUTING.md, PSGSuite/PSGSuite.psd1, PSGSuite/Public/Calendar/Get-GSCalendar.ps1, PSGSuite/Public/Calendar/Get-GSCalendarSubscription.ps1, PSGSuite/Public/Data Transfer/Get-GSDataTransfer.ps1, PSGSuite/Public/Drive/Start-GSDriveFileUpload.ps1, PSGSuite/Public/Resources/Update-GSResource.ps1, README.md, build.ps1
* [Issue #235](https://github.com/scrthq/PSGSuite/issues/235)
* Removed: `Name` parameter from `Start-GSDriveFileUpload` as it was unused in the function and doesnt make sense when uploading an array of files.
* [Issue #238](https://github.com/scrthq/PSGSuite/issues/238)
* Added: `Get-GSDataTransfer` to Get/List current Data Transfers
* [Issue #239](https://github.com/scrthq/PSGSuite/issues/239)
* Removed: `Update-GSResource` `Id` parameter as it was non-applicable (duplicate of `ResourceId` and not writable per API docs)
* Cleaned up function help and examples to match changes
* [Issue #240](https://github.com/scrthq/PSGSuite/issues/240)
* Fixed: `Get-GSCalendar` now properly resolves single calendar metadata retrieval and passes List requests to `Get-GSCalendarSubscription` since the …
=> !deploy v2.33.1 release

CHANGELOG.md, PSGSuite/PSGSuite.psd1, PSGSuite/Public/Calendar/New-GSCalendarEvent.ps1, README.md
Fixes #245.
This PR adds the switch parameter `-CreateMeetEvent` to `New-GSCalendarEvent` to create Google Meet conferences and attach them to the calendar event.
=> !deploy v2.34.0

PSGSuite/Public/Gmail/Get-GSGmailMessageList.ps1
Since we already run "foreach" on the $User, thought we can allow this to be an Array String input.
I have also tested it, and it works as expected, I got the multiple user output for my search.
=> Allow array input for $User

PSGSuite/Private/LicenseHelpers.ps1, PSGSuite/Public/Licensing/Get-GSUserLicense.ps1, PSGSuite/Public/Licensing/Remove-GSUserLicense.ps1, PSGSuite/Public/Licensing/Set-GSUserLicense.ps1, PSGSuite/Public/Licensing/Update-GSUserLicense.ps1
This is my first time using GIT so I hope I get this right.
I have added in the product IDs and SKUs for G-Suite Enterprise for Education as found from here: https://developers.google.com/admin-sdk/licensing/v1/how-tos/products
I couldn't figure out how to build the module to test my changes. So although this looks correct I have not yet tested it.
=> Added G-Suite Enterprise for Education licence

PSGSuite/Public/Drive/Get-GSDriveFileList.ps1, PSGSuite/Public/Drive/Remove-GSDriveFile.ps1
This PR includes changes to the Remove-GSDriveFile cmdlet, moving invariants to the Begin clause and introducing parameter sets. The new InputObject parameter provides for deleting either a File[] or pipelined File objects (from Get-GSDriveFileList, for example). The FileId parameter is made optional to preclude prompting. FileId and InputObject are mutually exclusive, but leaving both unset is okay - nothing happens.
=> new InputObject parameter

PSGSuite/Public/Authentication/New-GoogleService.ps1, PSGSuite/Public/Configuration/Get-PSGSuiteConfig.ps1, PSGSuite/Public/Configuration/Set-PSGSuiteConfig.ps1
This isn't fully ready to be merged, but I wanted to open this PR to see how you feel about these changes.
I'm trying to migrate from a Google API module my team has written, [UMN-Google](https://github.com/umn-microsoft-automation/UMN-Google), to this module.  Our primary use case is running from within Azure Automation.  Additionally, We're currently using a service account with a .p12 cert to do all our authentication, though our .p12 isn't a super admin, it's just a "regular" user in our domain.  Additionally, when we first created our .p12 cert we re-exported it with a new more secure password, instead of `notasecret`.
So the first change I've made here is to create a `P12KeyPassword` config item.  It can be specified with `Set-PSGSuiteConfig`.  If it exists, `New-GoogleService` will …
=> Improved P12 handling

PSGSuite/Public/Delegation/Remove-GSGmailDelegate.ps1
$origError is never populated therefor the error that comes out is not helpful.
=> Bugfix - missing Error variable
